[build]
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=3600"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=60, s-maxage=3600"
